# Generated by Django 2.2.4 on 2019-08-14 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='user',
        ),
        migrations.RemoveField(
            model_name='metricgroup',
            name='group',
        ),
        migrations.RemoveField(
            model_name='metricgroup',
            name='metric',
        ),
        migrations.RemoveField(
            model_name='metricgroup',
            name='user',
        ),
        migrations.RemoveField(
            model_name='threshold',
            name='metricgroup',
        ),
        migrations.RemoveField(
            model_name='threshold',
            name='user',
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='alarm',
        ),
        migrations.RemoveField(
            model_name='trigger',
            name='user',
        ),
        migrations.DeleteModel(
            name='Alarm',
        ),
        migrations.DeleteModel(
            name='Group',
        ),
        migrations.DeleteModel(
            name='MetricGroup',
        ),
        migrations.DeleteModel(
            name='Threshold',
        ),
        migrations.DeleteModel(
            name='Trigger',
        ),
    ]
