# Generated by Django 2.2.6 on 2019-10-09 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nslc', '0004_auto_20191008_1953'),
        ('measurement', '0002_remove_measurement_updated_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='measurement',
            unique_together={('metric', 'channel', 'starttime', 'endtime')},
        ),
    ]
