# Generated by Django 2.2.6 on 2019-10-15 22:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0003_auto_20191009_1936'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='measurement',
            unique_together=set(),
        ),
    ]
