# Generated by Django 2.2.6 on 2019-10-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0004_auto_20191015_2258'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['-starttime'], name='measurement_startti_7d7fa1_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['-endtime'], name='measurement_endtime_e347a7_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['value'], name='measurement_value_520b79_idx'),
        ),
        migrations.AddIndex(
            model_name='metric',
            index=models.Index(fields=['name'], name='measurement_name_26b7ed_idx'),
        ),
    ]
