# Generated by Django 2.2.6 on 2019-10-25 19:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0006_threshold'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='widget',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='dashboard.Widget'),
        ),
    ]
