# Generated by Django 2.2.6 on 2019-10-31 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0007_auto_20191025_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='default_maxval',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='metric',
            name='default_minval',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
