# Generated by Django 2.2.6 on 2019-11-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0008_auto_20191031_2026'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='default_maxval',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='default_minval',
            field=models.FloatField(blank=True),
        ),
    ]
