# Generated by Django 2.2.6 on 2019-11-21 17:51

from django.db import migrations, models
from measurement.models import Metric


class Migration(migrations.Migration):
    def set_defaults(name, count=0):
        '''set defaults. This needs to be done in three steps
            1) make field nullabe
            2) update all codes = name, ensure uniqueness by appending number
            3) set code to be unique and required 
            4) profit
        '''
        metrics = Metric.objects.all()
        unique_metrics = []
        def check_unique(name=name, count=count):
            '''be lazy and just append incremented number '''
            if name in unique_metrics:
                name = name + str(count)
                count += 1
                check_unique(name, count)
            else:
                unique_metrics.append(name)
                return name

        
        for m in metrics:
            name = m.name
            m.code = check_unique(name)
            m.save()
        

    dependencies = [
        ('measurement', '0009_auto_20191102_1653'),
    ]
    # added the migrations.RunPython and migrations.Alterfield by hand 
    operations = [
        migrations.AddField(
            model_name='metric',
            name='code',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.RunPython(set_defaults),
        migrations.AlterField(
            model_name='metric',
            name='code',
            field=models.CharField(max_length=255, unique=True)
        )
    ]
