# Generated by Django 2.2.6 on 2019-11-21 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0010_metric_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='code',
            field=models.CharField(default='temp', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
