# Generated by Django 2.2.8 on 2019-12-17 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nslc', '0005_auto_20191017_1758'),
        ('measurement', '0011_auto_20191121_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=8, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('mean', models.FloatField()),
                ('median', models.FloatField()),
                ('stdev', models.FloatField()),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('archive_type_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.ArchiveType')),
                ('channel_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nslc.Channel')),
                ('metric_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Metric')),
            ],
        ),
    ]
