# Generated by Django 2.2.9 on 2020-01-02 20:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nslc', '0005_auto_20191017_1758'),
        ('measurement', '0011_auto_20191121_2213'),
    ]

    operations = [
        migrations.CreateModel(
            name='Archive',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archive_type', models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month'), ('year', 'Year')], max_length=8)),
                ('min', models.FloatField()),
                ('max', models.FloatField()),
                ('mean', models.FloatField()),
                ('median', models.FloatField()),
                ('stdev', models.FloatField()),
                ('n', models.IntegerField()),
                ('starttime', models.DateTimeField()),
                ('endtime', models.DateTimeField()),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='nslc.Channel')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='measurement.Metric')),
            ],
        ),
    ]
