# Generated by Django 2.2.9 on 2020-01-30 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0012_archive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='maxval',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='threshold',
            name='minval',
            field=models.FloatField(blank=True),
        ),
    ]
