# Generated by Django 2.2.8 on 2019-12-18 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0012_archive_archivetype'),
    ]

    operations = [
        migrations.RenameField(
            model_name='archive',
            old_name='end_time',
            new_name='endtime',
        ),
        migrations.RenameField(
            model_name='archive',
            old_name='start_time',
            new_name='starttime',
        ),
    ]
