# Generated by Django 2.2.11 on 2020-03-26 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0014_auto_20200325_2153'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='url',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
