# Generated by Django 2.2.11 on 2020-03-31 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0015_auto_20200326_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='metric',
            name='reference_url',
            field=models.CharField(default='https://pnsn.org', max_length=255),
            preserve_default=False,
        ),
    ]
