# Generated by Django 2.2.12 on 2020-06-02 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0016_metric_reference_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metric',
            name='default_maxval',
            field=models.FloatField(blank=True),
        ),
        migrations.AlterField(
            model_name='metric',
            name='default_minval',
            field=models.FloatField(blank=True),
        ),
    ]
