# Generated by Django 2.2.16 on 2020-09-18 22:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nslc', '0008_auto_20200728_1909'),
        ('measurement', '0017_auto_20200609_0533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alarms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interval_type', models.CharField(max_length=255)),
                ('interval_count', models.PositiveIntegerField()),
                ('channel_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarms', to='nslc.Group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
