# Generated by Django 2.2.16 on 2020-10-13 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0017_auto_20200609_0533'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='measurement',
            name='measurement_endtime_e347a7_idx',
        ),
        migrations.RemoveIndex(
            model_name='measurement',
            name='measurement_value_520b79_idx',
        ),
    ]
