# Generated by Django 2.2.16 on 2020-09-22 22:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('measurement', '0019_threshold_band_inclusive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threshold',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='thresholds', to='measurement.Metric'),
        ),
        migrations.CreateModel(
            name='AlarmMetric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('minval', models.FloatField(blank=True, null=True)),
                ('maxval', models.FloatField(blank=True, null=True)),
                ('band_inclusive', models.BooleanField(default=True)),
                ('stat', models.CharField(max_length=255)),
                ('weight', models.FloatField(blank=True, null=True)),
                ('alarm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_metrics', to='measurement.Alarms')),
                ('metric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_metrics', to='measurement.Metric')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
