# Generated by Django 2.2.16 on 2020-09-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0020_auto_20200922_2226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmmetric',
            name='weight',
            field=models.FloatField(default=1),
        ),
    ]
