# Generated by Django 2.2.16 on 2020-10-23 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0025_auto_20201013_1629'),
        ('measurement', '0018_auto_20201013_2006'),
    ]

    operations = [
    ]
