# Generated by Django 3.1.2 on 2020-11-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0026_merge_20201023_1617'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarm',
            name='interval_type',
            field=models.CharField(choices=[('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day')], default='hour', max_length=8),
        ),
        migrations.AlterField(
            model_name='alarm',
            name='stat',
            field=models.CharField(choices=[('count', 'Count'), ('sum', 'Sum'), ('avg', 'Avg'), ('min', 'Min'), ('max', 'Max')], default='sum', max_length=8),
        ),
        migrations.AlterField(
            model_name='archive',
            name='archive_type',
            field=models.CharField(choices=[('day', 'Day'), ('week', 'Week'), ('month', 'Month')], max_length=8),
        ),
    ]
