# Generated by Django 3.1.2 on 2020-11-19 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0027_auto_20201104_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alarmthreshold',
            name='level',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three')], default=1),
        ),
    ]
