# Generated by Django 3.1.2 on 2020-11-20 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0028_auto_20201119_1900'),
        ('measurement', '0019_auto_20201119_0052'),
    ]

    operations = [
    ]
