# Generated by Django 3.1.2 on 2021-01-06 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0030_metric_sample_rate'),
        ('measurement', '0031_alarm_name'),
    ]

    operations = [
    ]
