# Generated by Django 3.1.2 on 2021-01-11 20:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nslc', '0008_auto_20200728_1909'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('measurement', '0032_merge_20210106_1849'),
    ]

    operations = [
        migrations.RenameModel('Alarm', 'Monitor'),
        migrations.AlterField(
            model_name='alarmthreshold',
            name='alarm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alarm_thresholds', to='measurement.monitor'),
        ),
    ]
