# Generated by Django 3.1.2 on 2021-01-11 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nslc', '0008_auto_20200728_1909'),
        ('measurement', '0033_auto_20210111_2024'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alarmthreshold',
            old_name='alarm',
            new_name='monitor',
        ),
        migrations.AlterField(
            model_name='monitor',
            name='channel_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='nslc.group'),
        ),
        migrations.AlterField(
            model_name='monitor',
            name='metric',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='monitors', to='measurement.metric'),
        ),
    ]
