# Generated by Django 3.1.2 on 2021-01-11 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('measurement', '0034_auto_20210111_2127'),
    ]

    operations = [
        migrations.RenameModel('AlarmThreshold', 'Trigger'),
        migrations.AlterField(
            model_name='alert',
            name='alarm_threshold',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='alerts', to='measurement.trigger'),
        ),
    ]
