# Generated by Django 3.1.2 on 2021-01-11 21:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0035_auto_20210111_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='alert',
            old_name='alarm_threshold',
            new_name='trigger',
        ),
        migrations.AlterField(
            model_name='trigger',
            name='monitor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='triggers', to='measurement.monitor'),
        ),
    ]
