# Generated by Django 3.1.2 on 2021-01-27 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0031_auto_20210120_0707'),
        ('measurement', '0036_auto_20210111_2149'),
    ]

    operations = [
    ]
