# Generated by Django 3.1.6 on 2021-04-14 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0037_merge_20210127_0735'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='archiveday',
            index=models.Index(fields=['-starttime'], name='measurement_startti_f3954b_idx'),
        ),
        migrations.AddIndex(
            model_name='archivehour',
            index=models.Index(fields=['-starttime'], name='measurement_startti_7e5cc1_idx'),
        ),
        migrations.AddIndex(
            model_name='archivemonth',
            index=models.Index(fields=['-starttime'], name='measurement_startti_077f72_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveweek',
            index=models.Index(fields=['-starttime'], name='measurement_startti_40a243_idx'),
        ),
    ]
