# Generated by Django 3.1.12 on 2021-09-14 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0039_auto_20210423_2203'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='reverse_monitor',
            field=models.BooleanField(default=False),
        ),
    ]
