# Generated by Django 3.1.12 on 2021-09-15 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0040_monitor_reverse_monitor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitor',
            old_name='reverse_monitor',
            new_name='invert_monitor',
        ),
    ]
