# Generated by Django 3.1.12 on 2021-11-24 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0042_alert_breaching_channels'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='alert_for_channel_dropout',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='monitor',
            name='alert_for_channel_join',
            field=models.BooleanField(default=False),
        ),
    ]
