# Generated by Django 3.1.12 on 2022-01-06 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0042_alert_breaching_channels'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='num_channels',
        ),
        migrations.AddField(
            model_name='trigger',
            name='num_channels',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
