# Generated by Django 3.1.12 on 2021-11-24 20:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0043_auto_20211124_1721'),
    ]

    operations = [
        migrations.RenameField(
            model_name='monitor',
            old_name='alert_for_channel_join',
            new_name='alert_for_channel_added',
        ),
        migrations.RenameField(
            model_name='monitor',
            old_name='alert_for_channel_dropout',
            new_name='alert_for_channel_removed',
        ),
    ]
