# Generated by Django 3.1.12 on 2022-01-06 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0043_auto_20220106_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='monitor',
            name='invert_monitor',
        ),
        migrations.AddField(
            model_name='trigger',
            name='invert_trigger',
            field=models.BooleanField(default=False),
        ),
    ]
