# Generated by Django 3.1.12 on 2022-01-12 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0044_auto_20220106_2300'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='num_channels_operator',
            field=models.CharField(choices=[('any', 'Any'), ('==', 'Equal to'), ('<', 'Less than'), ('>', 'Greater than')], default='<', max_length=16),
        ),
        migrations.AddField(
            model_name='trigger',
            name='value_operator',
            field=models.CharField(choices=[('outsideof', 'Outside of'), ('within', 'Within'), ('==', 'Equal to'), ('<', 'Less than'), ('<=', 'Less than or equal to'), ('>', 'Greater than'), ('>=', 'Greater than or equal to')], default='>', max_length=16),
        ),
    ]
