# Generated by Django 3.1.12 on 2022-01-13 00:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0045_auto_20220112_1848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trigger',
            name='band_inclusive',
        ),
    ]
