# Generated by Django 3.1.12 on 2022-01-13 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0046_remove_trigger_band_inclusive'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trigger',
            name='invert_trigger',
        ),
        migrations.AlterField(
            model_name='trigger',
            name='num_channels_operator',
            field=models.CharField(choices=[('any', 'Any'), ('==', 'Equal to'), ('<', 'Less than'), ('>', 'Greater than')], default='>', max_length=16),
        ),
    ]
