# Generated by Django 3.1.12 on 2022-01-13 17:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0049_auto_20220113_1646'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='alert_on_out_of_alarm',
            field=models.BooleanField(default=False),
        ),
    ]
