# Generated by Django 3.1.12 on 2022-03-22 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0050_trigger_alert_on_out_of_alarm'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='email_list',
            field=models.JSONField(null=True),
        ),
    ]
