# Generated by Django 3.1.12 on 2022-04-05 16:06

from django.db import migrations, models
import measurement.validators


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0051_trigger_email_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='email_list',
            field=models.JSONField(blank=True, null=True, validators=[measurement.validators.validate_email_list]),
        ),
    ]
