# Generated by Django 3.1.12 on 2022-04-21 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0053_remove_trigger_level'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='num_channels_operator',
            field=models.CharField(choices=[('any', 'Any'), ('all', 'All'), ('==', 'Equal to'), ('<', 'Less than'), ('>', 'Greater than')], default='>', max_length=16),
        ),
    ]
