# Generated by Django 3.1.13 on 2022-05-20 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0054_auto_20220421_1810'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Threshold',
        ),
    ]
