# Generated by Django 3.1.13 on 2023-02-01 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0055_delete_threshold'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alert',
            name='message',
        ),
        migrations.AlterField(
            model_name='monitor',
            name='interval_type',
            field=models.CharField(choices=[('minute', 'Minute'), ('hour', 'Hour'), ('day', 'Day'), ('last n', 'Last N')], default='hour', max_length=8),
        ),
    ]
