# Generated by Django 3.1.13 on 2023-02-22 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0056_auto_20230201_0013'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='do_daily_digest',
            field=models.BooleanField(default=False),
        ),
    ]
