# Generated by Django 3.1.13 on 2023-03-27 23:42

from django.db import migrations, models
import measurement.validators


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0058_auto_20230327_2316'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='email_list',
            field=models.JSONField(blank=True, default=list, null=True, validators=[measurement.validators.validate_email_list]),
        ),
    ]
