# Generated by Django 3.1.13 on 2023-03-28 01:22

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0059_auto_20230327_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='emails',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, null=True, size=None),
        ),
    ]
