# Generated by Django 3.1.13 on 2023-03-30 20:27

from django.db import migrations, models
import measurement.fields


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0059_auto_20230327_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='trigger',
            name='emails',
            field=measurement.fields.EmailListArrayField(base_field=models.EmailField(blank=True, max_length=254, null=True), blank=True, null=True, size=None),
        ),
    ]
