# Generated by Django 3.1.13 on 2023-03-28 01:39

from django.db import migrations, models
import measurement.fields


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0060_trigger_emails'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='emails',
            field=measurement.fields.EmailListArrayField(base_field=models.EmailField(max_length=254), blank=True, null=True, size=None),
        ),
    ]
