# Generated by Django 3.1.13 on 2025-05-01 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0061_remove_trigger_email_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archiveday',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='archivehour',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='archivemonth',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='archiveweek',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
