# Generated by Django 4.2.7 on 2024-02-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0061_remove_trigger_email_list'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='measurement',
            constraint=models.UniqueConstraint(fields=('metric', 'channel', 'starttime'), name='unique on starttime'),
        ),
    ]
