# Generated by Django 4.2.7 on 2024-02-08 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0062_measurement_unique_on_starttime'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='archiveday',
            index=models.Index(fields=['metric'], name='measurement_metric__fa134a_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveday',
            index=models.Index(fields=['channel'], name='measurement_channel_f4d0f9_idx'),
        ),
        migrations.AddIndex(
            model_name='archivehour',
            index=models.Index(fields=['metric'], name='measurement_metric__82bb1e_idx'),
        ),
        migrations.AddIndex(
            model_name='archivehour',
            index=models.Index(fields=['channel'], name='measurement_channel_1b39bb_idx'),
        ),
        migrations.AddIndex(
            model_name='archivemonth',
            index=models.Index(fields=['metric'], name='measurement_metric__562011_idx'),
        ),
        migrations.AddIndex(
            model_name='archivemonth',
            index=models.Index(fields=['channel'], name='measurement_channel_faef30_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveweek',
            index=models.Index(fields=['metric'], name='measurement_metric__88e6bd_idx'),
        ),
        migrations.AddIndex(
            model_name='archiveweek',
            index=models.Index(fields=['channel'], name='measurement_channel_887a5d_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['metric'], name='measurement_metric__d34887_idx'),
        ),
        migrations.AddIndex(
            model_name='measurement',
            index=models.Index(fields=['channel'], name='measurement_channel_e743cf_idx'),
        ),
    ]
