# Generated by Django 3.1.13 on 2023-03-29 00:06

from django.db import migrations, models
import measurement.fields


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0062_auto_20230328_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trigger',
            name='emails',
            field=measurement.fields.EmailListArrayField(base_field=models.EmailField(blank=True, max_length=254, null=True), blank=True, default=list, null=True, size=None),
        ),
    ]
