# Generated by Django 4.2.7 on 2025-09-12 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('measurement', '0062_auto_20250501_1852'),
        ('measurement', '0063_archiveday_measurement_metric__fa134a_idx_and_more'),
    ]

    operations = [
    ]
