# Generated by Django 2.2.6 on 2019-10-03 20:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nslc', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('code', 'network', 'station_code', 'loc')},
        ),
    ]
