# Generated by Django 2.2.6 on 2019-10-06 17:53

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('nslc', '0002_auto_20191003_2006'),
    ]

    operations = [
        migrations.AddField(
            model_name='channel',
            name='azimuth',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='channel',
            name='depth',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='channel',
            name='dip',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='channel',
            name='endtime',
            field=models.DateTimeField(default=datetime.datetime(2599, 12, 31, 0, 0, tzinfo=utc)),
        ),
        migrations.AddField(
            model_name='channel',
            name='scale',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='channel',
            name='scale_freq',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='channel',
            name='scale_units',
            field=models.CharField(default='M/S', max_length=10),
        ),
        migrations.AddField(
            model_name='channel',
            name='sensor_description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='channel',
            name='starttime',
            field=models.DateTimeField(default=datetime.datetime(1970, 1, 1, 0, 0, tzinfo=utc)),
        ),
    ]
