# Generated by Django 2.2.6 on 2019-10-17 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nslc', '0004_auto_20191008_1953'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['station_code'], name='nslc_channe_station_a0d176_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['station_name'], name='nslc_channe_station_f56e1b_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['loc'], name='nslc_channe_loc_3c0c29_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['lat'], name='nslc_channe_lat_533aec_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['lon'], name='nslc_channe_lon_1d0a17_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['-starttime'], name='nslc_channe_startti_1fcdf0_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['-endtime'], name='nslc_channe_endtime_5cec49_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['is_public'], name='nslc_group_is_publ_f5d8fc_idx'),
        ),
        migrations.AddIndex(
            model_name='network',
            index=models.Index(fields=['code'], name='nslc_networ_code_604d7d_idx'),
        ),
        migrations.AddIndex(
            model_name='network',
            index=models.Index(fields=['name'], name='nslc_networ_name_9c2503_idx'),
        ),
    ]
