# Generated by Django 2.2.12 on 2020-07-20 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('nslc', '0006_auto_20200331_1805'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='group',
            name='nslc_group_is_publ_f5d8fc_idx',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='is_public',
            new_name='share_all',
        ),
        migrations.AddField(
            model_name='group',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='channel_groups', to='organization.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='share_org',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['share_all'], name='nslc_group_share_a_f11af6_idx'),
        ),
        migrations.AddIndex(
            model_name='group',
            index=models.Index(fields=['share_org'], name='nslc_group_share_o_e0f17a_idx'),
        ),
    ]
