# Generated by Django 3.1.8 on 2021-04-29 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nslc', '0008_auto_20200728_1909'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='group',
            name='nslc_group_share_a_f11af6_idx',
        ),
        migrations.RemoveIndex(
            model_name='group',
            name='nslc_group_share_o_e0f17a_idx',
        ),
        migrations.RemoveField(
            model_name='group',
            name='share_all',
        ),
        migrations.RemoveField(
            model_name='group',
            name='share_org',
        ),
    ]
