# Generated by Django 3.1.13 on 2022-05-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nslc', '0009_auto_20210429_2335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
