# Generated by Django 3.1.13 on 2022-05-25 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nslc', '0010_auto_20220513_2049'),
        ('nslc', '0010_auto_20220525_1729'),
    ]

    operations = [
    ]
