# Generated by Django 3.1.13 on 2022-07-22 17:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import regex_field.fields


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('nslc', '0010_auto_20220525_1729'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='auto_exclude_channels',
            field=models.ManyToManyField(related_name='_group_auto_exclude_channels_+', to='nslc.Channel'),
        ),
        migrations.AddField(
            model_name='group',
            name='auto_include_channels',
            field=models.ManyToManyField(related_name='_group_auto_include_channels_+', to='nslc.Channel'),
        ),
        migrations.CreateModel(
            name='MatchingRule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network_regex', regex_field.fields.RegexField(default='.*', max_length=128)),
                ('station_regex', regex_field.fields.RegexField(default='.*', max_length=128)),
                ('location_regex', regex_field.fields.RegexField(default='.*', max_length=128)),
                ('channel_regex', regex_field.fields.RegexField(default='.*', max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_include', models.BooleanField(default=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='matching_rules', to='nslc.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
