# Generated by Django 3.1.13 on 2022-07-25 20:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('nslc', '0011_merge_20220525_1858'),
        ('nslc', '0011_auto_20220722_1736'),
    ]

    operations = [
    ]
