# Generated by Django 3.1.13 on 2022-08-16 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nslc', '0012_merge_20220725_2021'),
    ]
    
    operations = [
        migrations.AddField(
            model_name='channel',
            name='nslc',
            field=models.CharField(null=True, max_length=255),
        ),
    ]

