# Generated by Django 3.1.13 on 2022-08-17 01:09

from django.db import migrations
import regex_field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('nslc', '0015_auto_20220817_0104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matchingrule',
            name='channel_regex',
            field=regex_field.fields.RegexField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='matchingrule',
            name='location_regex',
            field=regex_field.fields.RegexField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='matchingrule',
            name='network_regex',
            field=regex_field.fields.RegexField(blank=True, default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='matchingrule',
            name='station_regex',
            field=regex_field.fields.RegexField(blank=True, default='', max_length=128),
        ),
    ]
