# Generated by Django 3.1.13 on 2022-09-15 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nslc', '0016_auto_20220817_0109'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='share_all',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='group',
            name='share_org',
            field=models.BooleanField(default=False),
        ),
    ]
