# Generated by Django 3.1.13 on 2022-09-17 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nslc', '0017_auto_20220915_1819'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='channels',
            field=models.ManyToManyField(related_name='channel_group', to='nslc.Channel'),
        ),
    ]
