# Generated by Django 3.1.13 on 2022-09-17 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nslc', '0018_auto_20220917_0049'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='channels',
            field=models.ManyToManyField(related_name='_group_channels_+', to='nslc.Channel'),
        ),
    ]
