# Generated by Django 3.1.13 on 2022-09-19 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nslc', '0019_auto_20220917_0051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='channels',
            field=models.ManyToManyField(to='nslc.Channel'),
        ),
    ]
