# Generated by Django 3.1.13 on 2022-10-04 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nslc', '0020_auto_20220919_2123'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='channel',
            name='nslc_channe_station_a0d176_idx',
        ),
        migrations.RemoveIndex(
            model_name='channel',
            name='nslc_channe_station_f56e1b_idx',
        ),
        migrations.RenameField(
            model_name='channel',
            old_name='network',
            new_name='net',
        ),
        migrations.RenameField(
            model_name='channel',
            old_name='station_code',
            new_name='sta',
        ),
        migrations.RenameField(
            model_name='channel',
            old_name='station_name',
            new_name='sta_name',
        ),
        migrations.AlterUniqueTogether(
            name='channel',
            unique_together={('code', 'net', 'sta', 'loc')},
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['sta'], name='nslc_channe_sta_7012f1_idx'),
        ),
        migrations.AddIndex(
            model_name='channel',
            index=models.Index(fields=['sta_name'], name='nslc_channe_sta_nam_70e399_idx'),
        ),
    ]
