# Generated by Django 4.2.7 on 2024-02-08 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nslc', '0020_auto_20220919_2123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='auto_exclude_channels',
            field=models.ManyToManyField(related_name='+', to='nslc.channel'),
        ),
        migrations.AlterField(
            model_name='group',
            name='auto_include_channels',
            field=models.ManyToManyField(related_name='+', to='nslc.channel'),
        ),
    ]
