# Generated by Django 2.2.10 on 2020-03-05 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='firstname',
        ),
        migrations.AddField(
            model_name='user',
            name='lastname',
            field=models.CharField(default='namegoeshere', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='organization',
            field=models.CharField(default='PNSN', max_length=255),
            preserve_default=False,
        ),
    ]
