# Generated by Django 3.1.2 on 2020-10-30 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_notification'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='notification',
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('slack', 'Slack')], default='email', max_length=255),
        ),
    ]
