# Generated by Django 3.1.2 on 2020-12-04 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20201030_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='value',
            field=models.CharField(default='', max_length=255),
        ),
    ]
