# Generated by Django 3.1.2 on 2020-12-07 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_notification_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='level',
            field=models.IntegerField(choices=[(1, 'One'), (2, 'Two'), (3, 'Three')], default=1),
        ),
    ]
