# Generated by Django 3.1.2 on 2021-01-08 22:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='notification',
            name='value',
        ),
        migrations.AddField(
            model_name='notification',
            name='contact',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='core.contact'),
        ),
    ]
