# Generated by Django 2.2.12 on 2020-06-29 22:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('org', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Institution',
        ),
        migrations.DeleteModel(
            name='InstitutionUser',
        ),
    ]
