# Generated by Django 2.2.4 on 2019-08-16 15:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Widget_Type',
            new_name='WidgetType',
        ),
        migrations.RenameField(
            model_name='widget',
            old_name='widget_type',
            new_name='widgettype',
        ),
    ]
