# Generated by Django 2.2.6 on 2019-10-16 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20191016_2341'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='stattype',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='stat', to='dashboard.StatType'),
            preserve_default=False,
        ),
    ]
