# Generated by Django 2.2.6 on 2019-10-31 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_auto_20191017_1758'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='columns',
            field=models.IntegerField(default=6),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='widget',
            name='order',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='widget',
            name='rows',
            field=models.IntegerField(default=3),
            preserve_default=False,
        ),
    ]
