# Generated by Django 2.2.6 on 2019-11-20 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20191031_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='order',
        ),
        migrations.AddField(
            model_name='widget',
            name='x_postion',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='widget',
            name='y_position',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
