# Generated by Django 2.2.6 on 2019-11-20 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20191120_2057'),
    ]

    operations = [
        migrations.RenameField(
            model_name='widget',
            old_name='x_postion',
            new_name='x_position',
        ),
    ]
