# Generated by Django 2.2.6 on 2019-12-05 19:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nslc', '0005_auto_20191017_1758'),
        ('dashboard', '0007_auto_20191120_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='group',
        ),
        migrations.AddField(
            model_name='widget',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='nslc.Group'),
            preserve_default=False,
        ),
    ]
