# Generated by Django 2.2.6 on 2019-12-05 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_auto_20191205_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='widget',
            old_name='group',
            new_name='channel_group',
        ),
    ]
