# Generated by Django 2.2.8 on 2019-12-11 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0009_auto_20191205_1958'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='channel_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='nslc.Group'),
        ),
        migrations.AlterField(
            model_name='widget',
            name='stattype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='dashboard.StatType'),
        ),
    ]
