# Generated by Django 2.2.12 on 2020-06-22 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_auto_20200128_0515'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='endtime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='starttime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='window_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
