# Generated by Django 2.2.12 on 2020-06-29 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_field_fix_and_editable'),
        ('dashboard', '0012_auto_20200622_2218'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='organizations.Organization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='widget',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='organizations.Organization'),
            preserve_default=False,
        ),
    ]
