# Generated by Django 2.2.14 on 2020-07-21 04:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
        ('dashboard', '0012_auto_20200622_2218'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='dashboard',
            name='dashboard_d_name_8857a6_idx',
        ),
        migrations.RenameField(
            model_name='dashboard',
            old_name='is_public',
            new_name='share_all',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='is_public',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='organization.Organization'),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='share_org',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['share_all'], name='dashboard_d_share_a_bcc8e7_idx'),
        ),
        migrations.AddIndex(
            model_name='dashboard',
            index=models.Index(fields=['share_org'], name='dashboard_d_share_o_3460ca_idx'),
        ),
    ]
