# Generated by Django 2.2.14 on 2020-07-28 19:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0013_auto_20200721_0440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='organization',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='dashboards', to='organization.Organization'),
            preserve_default=False,
        ),
    ]
