# Generated by Django 3.1.2 on 2020-11-19 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20200728_1909'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='color_palet',
            field=models.CharField(blank=True, default='squac', max_length=255),
        ),
    ]
