# Generated by Django 2.2.12 on 2020-07-08 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0014_auto_20200708_1958'),
    ]

    operations = [
        migrations.RenameField(
            model_name='widget',
            old_name='share_public',
            new_name='share_org',
        ),
    ]
