# Generated by Django 2.2.12 on 2020-07-10 00:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_auto_20200708_2101'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='organization',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='share_all',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='share_org',
        ),
    ]
