# Generated by Django 3.1.2 on 2020-11-19 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_widget_color_palet'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='color_palet',
        ),
        migrations.AddField(
            model_name='widget',
            name='color_pallet',
            field=models.CharField(choices=[('squac', 'Squac')], default='squac', max_length=24),
        ),
    ]
