# Generated by Django 3.1.2 on 2020-12-03 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0016_auto_20201119_1901'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='stattype',
            name='home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='widget',
            name='home',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='widgettype',
            name='home',
            field=models.BooleanField(default=False),
        ),
    ]
