# Generated by Django 3.1.2 on 2020-12-03 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0017_auto_20201203_0022'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stattype',
            name='home',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='home',
        ),
        migrations.RemoveField(
            model_name='widgettype',
            name='home',
        ),
    ]
