# Generated by Django 3.1.8 on 2021-04-26 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0019_dashboard_archive_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='widgettype',
            name='use_aggregate',
            field=models.BooleanField(default=False),
        ),
    ]
