# Generated by Django 3.1.8 on 2021-04-28 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0020_widgettype_use_aggregate'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='archive_stat',
            field=models.CharField(choices=[('mean', 'Mean'), ('median', 'Median'), ('stdev', 'Standard Deviation'), ('min', 'Min'), ('max', 'Max'), ('p05', '5th Percentile'), ('p10', '10th Percentile'), ('p90', '90th Percentile'), ('p95', '95th Percentile'), ('num_samps', 'Number of Samples')], default='mean', max_length=16),
        ),
    ]
