# Generated by Django 3.1.13 on 2022-05-13 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0021_dashboard_archive_stat'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboard',
            name='home',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='color_pallet',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='properties',
            field=models.JSONField(null=True),
        ),
        migrations.AddField(
            model_name='dashboard',
            name='widget',
            field=models.JSONField(null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='archive_stat',
            field=models.CharField(choices=[('mean', 'Mean'), ('median', 'Median'), ('stdev', 'Standard Deviation'), ('min', 'Min'), ('max', 'Max'), ('p05', '5th Percentile'), ('p10', '10th Percentile'), ('p90', '90th Percentile'), ('p95', '95th Percentile'), ('num_samps', 'Number of Samples')], default='mean', max_length=16, null=True),
        ),
        migrations.AlterField(
            model_name='dashboard',
            name='archive_type',
            field=models.CharField(choices=[('raw', 'Raw'), ('hour', 'Hour'), ('day', 'Day'), ('week', 'Week'), ('month', 'Month')], default='raw', max_length=8, null=True),
        ),
    ]
