# Generated by Django 3.1.13 on 2022-05-16 23:18

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0023_auto_20220516_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='widget',
            name='properties',
            field=models.JSONField(default=dashboard.models.Widget.widget_props, verbose_name='Properties'),
        ),
    ]
