# Generated by Django 3.1.13 on 2022-05-16 23:52

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0024_auto_20220516_2318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widgettype',
            name='user',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='archive_stat',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='archive_type',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='endtime',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='starttime',
        ),
        migrations.RemoveField(
            model_name='dashboard',
            name='window_seconds',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='columns',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='rows',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='stattype',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='widgettype',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='x_position',
        ),
        migrations.RemoveField(
            model_name='widget',
            name='y_position',
        ),
        migrations.AddField(
            model_name='widget',
            name='layout',
            field=models.JSONField(null=True, verbose_name='layout'),
        ),
        migrations.AddField(
            model_name='widget',
            name='type',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='widget',
            name='properties',
            field=models.JSONField(default=dashboard.models.Widget.widget_props, verbose_name='properties'),
        ),
        migrations.DeleteModel(
            name='StatType',
        ),
        migrations.DeleteModel(
            name='WidgetType',
        ),
    ]
