# Generated by Django 3.1.13 on 2022-05-20 23:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0026_auto_20220520_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='widget',
            name='thresholds',
            field=models.JSONField(null=True),
        ),
    ]
