# Generated by Django 3.1.13 on 2022-06-30 20:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nslc', '0011_merge_20220525_1858'),
        ('dashboard', '0027_widget_thresholds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='widget',
            name='channel_group',
        ),
        migrations.AddField(
            model_name='dashboard',
            name='channel_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='nslc.group'),
        ),
    ]
