# Generated by Django 3.1.13 on 2022-08-16 20:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nslc', '0012_merge_20220725_2021'),
        ('dashboard', '0028_auto_20220630_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='channel_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='widgets', to='nslc.group'),
        ),
    ]
