# Generated by Django 3.1.13 on 2022-08-31 23:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('nslc', '0016_auto_20220817_0109'),
        ('dashboard', '0029_auto_20220816_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboard',
            name='channel_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='widgets', to='nslc.group'),
        ),
    ]
